# Generated by Django 3.1.4 on 2020-12-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
